--奥利哈刚 阿拉克涅 （ZCG）
function c77239212.initial_effect(c)
	  --handes
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(77239212,0))
	e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F)
	e1:SetCode(EVENT_CONTROL_CHANGED)
	e1:SetOperation(c77239212.operation)
	c:RegisterEffect(e1)
end
function c77239212.operation(e,tp,eg,ep,ev,re,r,rp)
   local c=e:GetHandler()
	local e9=Effect.CreateEffect(c)
	e9:SetType(EFFECT_TYPE_SINGLE)
	e9:SetCode(EFFECT_CANNOT_ATTACK)
	e9:SetReset(RESETS_STANDARD+RESET_EVENT)
	c:RegisterEffect(e9)
 local e10=Effect.CreateEffect(c)
	e10:SetType(EFFECT_TYPE_SINGLE)
	e10:SetCode(EFFECT_CANNOT_CHANGE_POSITION)
	e10:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_COPY_INHERIT)
	e10:SetReset(RESET_EVENT+RESETS_STANDARD)
	c:RegisterEffect(e10)
local e1=Effect.CreateEffect(e:GetHandler())
			e1:SetType(EFFECT_TYPE_SINGLE)
			e1:SetCode(EFFECT_UNRELEASABLE_SUM)
			e1:SetValue(1)
			e1:SetReset(RESET_EVENT+RESETS_STANDARD)
			c:RegisterEffect(e1)
			local e3=e1:Clone()
			e3:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
			c:RegisterEffect(e3)
	  local e4=e3:Clone()
			e4:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
			c:RegisterEffect(e4)
 --recover
	local e0=Effect.CreateEffect(c)
	e0:SetCategory(CATEGORY_RECOVER+CATEGORY_DAMAGE)
	e0:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e0:SetCode(EVENT_PHASE+PHASE_STANDBY)
	e0:SetRange(LOCATION_MZONE)
	e0:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e0:SetCountLimit(1)
	e0:SetReset(RESET_EVENT+RESETS_STANDARD)
	e0:SetTarget(c77239212.rectg)
	e0:SetOperation(c77239212.recop)
	c:RegisterEffect(e0)
end
function c77239212.rectg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return true end
	Duel.SetTargetPlayer(tp)
	Duel.SetTargetParam(500)
	Duel.SetOperationInfo(0,CATEGORY_RECOVER,nil,0,tp,500)
end
function c77239212.recop(e,tp,eg,ep,ev,re,r,rp)
	local p,d=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
   Duel.Damage(1-tp,500,REASON_EFFECT)
	Duel.Recover(p,d,REASON_EFFECT)
end


